#!/bin/bash
#python3 -m compileall -b $PYFILE

# another method

#python3 -m compileall $PYFILE
#mv __pycache__/* "${PYFILE}c"
#rm -rf __pycache__i

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set"
    exit 1
fi

output_file="${PYFILE}c"
echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE" && mv "__pycache__/$PYFILE.cpython-*.pyc" "$output_file" && rm -rf "__pycache__"

